In [2]:
from bs4 import BeautifulSoup
import pandas as pd
# create dataframe with colomn ,movie name,rating,director name
file=open("30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ Rotten Tomatoes – Movie and TV News.html", encoding="utf-8")
responce=file.read()
soup=BeautifulSoup(responce,"html.parser")
movie=[]
rating=[]
director=[]
a=soup.find_all("div",class_="col-sm-18 col-full-xs countdown-item-content")
for i in a:
    movie.append(i.find("h2").find("a").text.strip())
    rating.append(i.find("span",class_="tMeterScore").text.strip())
    director.append(i.find("div",class_="info director").find("a").text.strip())
df=pd.DataFrame({"movie":movie,"rating":rating,"director":director})
df

                                      movie rating               director
0          Transformers: Rise of the Beasts    53%       Steven Caple Jr.
1       Spider-Man: Across the Spider-Verse    96%     Joaquim Dos Santos
2                        The Little Mermaid    67%           Rob Marshall
3                             The Boogeyman    63%             Rob Savage
4     Are You There God? It's Me, Margaret.    99%     Kelly Fremon Craig
5                                    Fast X    56%        Louis Leterrier
6                                BlackBerry    98%           Matt Johnson
7                               The Machine    27%          Peter Atencio
8                                   Reality    92%            Tina Satter
9                               Flamin' Hot    68%           Eva Longoria
10           Guardians of the Galaxy Vol. 3    82%             James Gunn
11                                Blue Jean    94%         Georgia Oakley
12                               Past Lives    97%            Celine Song
13              The Super Mario Bros. Movie    58%          Aaron Horvath
14                 Avatar: The Way of Water    76%          James Cameron
15               Guy Ritchie's The Covenant    83%            Guy Ritchie
16                                Bumblebee    91%          Travis Knight
17                                Nefarious    33%           Cary Solomon
18                                     Sisu    93%       Jalmari Helander
19                     You Hurt My Feelings    95%      Nicole Holofcener
20                     John Wick: Chapter 4    94%         Chad Stahelski
21                           Leave No Trace    80%           Irene Taylor
22                          About My Father    36%          Laura Terruso
23  Dungeons & Dragons: Honor Among Thieves    90%  Jonathan M. Goldstein
24                             Transformers    57%            Michael Bay
25                                 My Fault              Domingo González
26                         A Beautiful Life    50%             Mehdi Avaz
27     The Angry Black Girl and Her Monster    88%        Bomani J. Story
28                                  Missing    87%           Will Merrick
29                                      Air    92%            Ben Affleck

In [8]:
#Question 2:
# Write a python program to scrape the following file. Extract the data regarding the given mobiles and create dataframe accordingly:-
# Link to the file :- Indeed Jobs
# Required Output

from bs4 import BeautifulSoup
import pandas as pd
# create dataframe with colomn ,movie name,rating,director name
website="indeed jobs.html"
file=open(website, encoding="utf-8")
responce=file.read()
soup=BeautifulSoup(responce,"html.parser")
name_job=[]
company=[]
salary=[]
location=[]
import numpy as np
#print(a)
a=soup.find_all("div",class_="job_seen_beacon")
for i in a:
    name_job.append(i.find("h2",class_="jobTitle css-1psdjh5 eu4oa1w0").text.strip())
    company.append(i.find("div",class_="css-1afmp4o e37uo190").text.strip())
    location.append(i.find("div",class_="css-pt3vth e37uo190").text.strip())
    try:
        salary.append(i.find("div",class_="css-18z4q2i eu4oa1w0").text.strip())
    except:
        salary.append(np.nan)    
df=pd.DataFrame({"name_job":name_job,"company":company,"location":location,"salary":salary})
df

,name_job,company,location,salary
0,Junior Python Developer,Saltriver Infosystems Pvt Ltd,Junior Python Developer,"₹13,000 - ₹22,000 a month"
1,AI & ML - Trainee,Techify Solutions,AI & ML - Trainee,NaN
2,Python Developer Fresher,XcelTec,Python Developer Fresher,NaN
3,AI ML Python Developer,"Arrow Electronics, Inc.",AI ML Python Developer,Full-time
4,Trainee AI ML,Vrinsoft Technology,Trainee AI ML,NaN
5,Python Developer,Taasha Technologies,Python Developer,NaN
6,AI Engineer,PySquad Informatics LLP,AI Engineer,"₹50,000 - ₹70,000 a month"
7,Full Stack Developer Intern,JuniGadi.com,Full Stack Developer Intern,"₹15,000 - ₹20,000 a month"
8,Data Analyst,Anblicks,Data Analyst,NaN
9,Python Developer,Sufalam Technologies Private Ltd.,Python Developer,"₹50,000 - ₹55,000 a month"
10,AI & ML Technologies Specialist,Zydus Group,AI & ML Technologies Specialist,NaN
11,AI/ML Engineer,eSparkBiz Technologies Pvt. Ltd,AI/ML Engineer,"₹50,000 - ₹70,000 a month"
12,Python Developer,reverseBits Tech LLP,Python Developer,"From ₹20,000 a month"
13,Python Developer,Albiorix Technology,Python Developer,NaN
14,Python Developer Fresher,Xceltec Interactive Pvt ltd,Python Developer Fresher,"From ₹10,000 a month"

In [5]:
from bs4 import BeautifulSoup
import pandas as pd
# create dataframe with colomn ,movie name,rating,director name
website="SENSEX Top Gainers, BSE Daily Top Gainers - Stock Market.html"
file=open(website, encoding="utf-8")
responce=file.read()
soup=BeautifulSoup(responce,"html.parser")
a=soup.find("table")
#print(a)
company=[]
current_pr=[]
Prev_Close_Date=[]
Change=[]
change_per=[]
low=[]
high=[]
b=soup.find_all("tr")
for i in b[1:]:
    company.append(i.find("td",class_="v-align").text.strip())
    current_pr.append(i.find("td",class_="txt-right v-align").text.strip())
    # Prev_Close_Date.append(i.find("td",class_="txt-right v-align").find("small").text.strip())
    # Change.append(i.find("td",class_="txt-right v-align").text.strip())
    low.append(i.find("span",class_="fl f-9").text.strip())    
    high.append(i.find("span",class_="fr f-9").text.strip())
    c=i.find_all("td",class_="txt-ctr")   #jyare be class same hoy tyare aavu karavu pde
    print(c)
    for i in c[::2]:
        Change.append(i.text.strip())
    for i in c[1::2]:
        change_per.append(i.text.strip())    
    
print(len(company))
print(len(current_pr))
print(len(change_per))

df=pd.DataFrame({"company":company,"current_pr":current_pr,"Change":Change,"change_per":change_per,"low":low,"high":high})
df

[<td class="txt-ctr"><span class="green-btn">13.75</span></td>, <td class="txt-ctr"><span class="green-btn">2.41%</span></td>]
[<td class="txt-ctr"><span class="green-btn">19.20</span></td>, <td class="txt-ctr"><span class="green-btn">1.67%</span></td>]
[<td class="txt-ctr"><span class="green-btn">51.95</span></td>, <td class="txt-ctr"><span class="green-btn">1.64%</span></td>]
[<td class="txt-ctr"><span class="green-btn">2.85</span></td>, <td class="txt-ctr"><span class="green-btn">1.16%</span></td>]
[<td class="txt-ctr"><span class="green-btn">10.50</span></td>, <td class="txt-ctr"><span class="green-btn">0.81%</span></td>]
[<td class="txt-ctr"><span class="green-btn">2.25</span></td>, <td class="txt-ctr"><span class="green-btn">0.80%</span></td>]
[<td class="txt-ctr"><span class="green-btn">15.70</span></td>, <td class="txt-ctr"><span class="green-btn">0.66%</span></td>]
[<td class="txt-ctr"><span class="green-btn">44.45</span></td>, <td class="txt-ctr"><span class="green-btn">0.62%</span></td>]
[<td class="txt-ctr"><span class="green-btn">6.20</span></td>, <td class="txt-ctr"><span class="green-btn">0.39%</span></td>]
[<td class="txt-ctr"><span class="green-btn">17.15</span></td>, <td class="txt-ctr"><span class="green-btn">0.37%</span></td>]
[<td class="txt-ctr"><span class="green-btn">6.70</span></td>, <td class="txt-ctr"><span class="green-btn">0.25%</span></td>]
[<td class="txt-ctr"><span class="green-btn">0.35</span></td>, <td class="txt-ctr"><span class="green-btn">0.22%</span></td>]
[<td class="txt-ctr"><span class="green-btn">3.20</span></td>, <td class="txt-ctr"><span class="green-btn">0.10%</span></td>]
[<td class="txt-ctr"><span class="green-btn">0.05</span></td>, <td class="txt-ctr"><span class="green-btn">0.04%</span></td>]
14
14
14

              company current_pr Change change_per      low     high
0         Tata Motors     583.30  13.75      2.41%   562.40   584.00
1           HCL Tech.    1168.20  19.20      1.67%  1130.15  1170.00
2                 TCS    3227.20  51.95      1.64%  3201.60  3232.00
3   Power Grid Corpn.     248.95   2.85      1.16%   243.25   249.75
4             Infosys    1303.15  10.50      0.81%  1291.00  1304.40
5             Vedanta     282.60   2.25      0.80%   278.70   284.35
6     Larsen & Toubro    2382.20  15.70      0.66%  2355.00  2390.30
7       Bajaj Finance    7247.85  44.45      0.62%  7202.00  7375.00
8           HDFC Bank    1608.30   6.20      0.39%  1590.90  1610.95
9          Bajaj Auto    4659.90  17.15      0.37%  4570.70  4670.80
10               HDFC    2657.85   6.70      0.25%  2632.00  2663.25
11               ONGC     157.25   0.35      0.22%   156.60   157.80
12       Asian Paints    3318.40   3.20      0.10%  3276.30  3326.45
13         Tata Steel     114.30   0.05      0.04%   113.50   115.25

In [ ]:
#                           new topic
#rest api(representational state transfer application programming interface)
# H.W.api key generate  karavani

<!-- http://api.openweathermap.org/geo/1.0/direct?q={city name},{state code},{country code}&limit={limit}&appid={API key} -->

In [ ]:
import requests,json
url="http://api.openweathermap.org/geo/1.0/direct?q=+city,{state code},{country code}&limit={limit}&appid={API key}"http://api.openweathermap.org/geo/1.0/direct?q={city name},{state code},{country code}&limit={limit}&appid={API key}
city=input("enter city name")
api/-key="32b45e398e410de74bbb7bc204946c57"